
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetTemplateForSkuSoap", targetNamespace = "http://tempuri.org/")
public interface GetTemplateForSkuSoap {


    /**
     * 
     * @param typeTemplate
     * @param sku
     * @param user
     * @param pass
     * @return
     *     returns org.tempuri.TemplateMailItem
     */
    @WebMethod(operationName = "GetTemplateEmail", action = "http://tempuri.org/GetTemplateEmail")
    @WebResult(name = "GetTemplateEmailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTemplateEmail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTemplateEmail")
    @ResponseWrapper(localName = "GetTemplateEmailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTemplateEmailResponse")
    public TemplateMailItem getTemplateEmail(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "sku", targetNamespace = "http://tempuri.org/")
        String sku,
        @WebParam(name = "typeTemplate", targetNamespace = "http://tempuri.org/")
        int typeTemplate);

    /**
     * 
     * @param sku
     * @return
     *     returns org.tempuri.BrandIdAndProductTypeId
     */
    @WebMethod(operationName = "GetBrandIdAndProductTypeIdBySku", action = "http://tempuri.org/GetBrandIdAndProductTypeIdBySku")
    @WebResult(name = "GetBrandIdAndProductTypeIdBySkuResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBrandIdAndProductTypeIdBySku", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBrandIdAndProductTypeIdBySku")
    @ResponseWrapper(localName = "GetBrandIdAndProductTypeIdBySkuResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBrandIdAndProductTypeIdBySkuResponse")
    public BrandIdAndProductTypeId getBrandIdAndProductTypeIdBySku(
        @WebParam(name = "sku", targetNamespace = "http://tempuri.org/")
        String sku);

}
