
package fpt.sendemail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "RSendSMSService", targetNamespace = "http://sendEmail.fpt/", wsdlLocation = "http://localhost:8888/ecom/sendemail?wsdl")
public class RSendSMSService
    extends Service
{

    private final static URL RSENDSMSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/ecom/sendemail?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RSENDSMSSERVICE_WSDL_LOCATION = url;
    }

    public RSendSMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RSendSMSService() {
        super(RSENDSMSSERVICE_WSDL_LOCATION, new QName("http://sendEmail.fpt/", "RSendSMSService"));
    }

    /**
     * 
     * @return
     *     returns SendEmail
     */
    @WebEndpoint(name = "sendEmailPort")
    public SendEmail getSendEmailPort() {
        return (SendEmail)super.getPort(new QName("http://sendEmail.fpt/", "sendEmailPort"), SendEmail.class);
    }

}
