
package fpt.sendemail;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "sendEmail", targetNamespace = "http://sendEmail.fpt/")
public interface SendEmail {


    /**
     * 
     * @param subject
     * @param giaDen
     * @param tgMuaDen
     * @param passWord
     * @param mobileoperator
     * @param content
     * @param nameCamp
     * @param tgMuaTu
     * @param tgGui
     * @param loaiSP
     * @param giaTu
     * @param requestID
     * @param statusUpdate
     * @param nganhHang
     * @param userName
     * @param teamplate
     * @return
     *     returns int
     */
    @WebMethod(operationName = "campaign_Update")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "campaign_Update", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.CampaignUpdate")
    @ResponseWrapper(localName = "campaign_UpdateResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.CampaignUpdateResponse")
    public int campaignUpdate(
        @WebParam(name = "requestID", targetNamespace = "http://sendEmail.fpt/")
        String requestID,
        @WebParam(name = "statusUpdate", targetNamespace = "http://sendEmail.fpt/")
        String statusUpdate,
        @WebParam(name = "nameCamp", targetNamespace = "http://sendEmail.fpt/")
        String nameCamp,
        @WebParam(name = "nganhHang", targetNamespace = "http://sendEmail.fpt/")
        String nganhHang,
        @WebParam(name = "loaiSP", targetNamespace = "http://sendEmail.fpt/")
        String loaiSP,
        @WebParam(name = "giaTu", targetNamespace = "http://sendEmail.fpt/")
        Long giaTu,
        @WebParam(name = "giaDen", targetNamespace = "http://sendEmail.fpt/")
        Long giaDen,
        @WebParam(name = "tgMuaTu", targetNamespace = "http://sendEmail.fpt/")
        String tgMuaTu,
        @WebParam(name = "tgMuaDen", targetNamespace = "http://sendEmail.fpt/")
        String tgMuaDen,
        @WebParam(name = "tgGui", targetNamespace = "http://sendEmail.fpt/")
        String tgGui,
        @WebParam(name = "teamplate", targetNamespace = "http://sendEmail.fpt/")
        String teamplate,
        @WebParam(name = "subject", targetNamespace = "http://sendEmail.fpt/")
        String subject,
        @WebParam(name = "content", targetNamespace = "http://sendEmail.fpt/")
        String content,
        @WebParam(name = "mobileoperator", targetNamespace = "http://sendEmail.fpt/")
        String mobileoperator,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param requestID
     * @param typeCamp
     * @param userName
     * @param passWord
     * @return
     *     returns fpt.sendemail.BReportCamp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReport", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.GetReport")
    @ResponseWrapper(localName = "getReportResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.GetReportResponse")
    public BReportCamp getReport(
        @WebParam(name = "requestID", targetNamespace = "http://sendEmail.fpt/")
        String requestID,
        @WebParam(name = "typeCamp", targetNamespace = "http://sendEmail.fpt/")
        int typeCamp,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param content
     * @param to
     * @param urlpush
     * @param emailId
     * @param subject
     * @param bcc
     * @param userName
     * @param teamplate
     * @param orderid
     * @param from
     * @param passWord
     * @param cc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.SendEmail_Type")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.SendEmailResponse")
    public String sendEmail(
        @WebParam(name = "from", targetNamespace = "http://sendEmail.fpt/")
        String from,
        @WebParam(name = "to", targetNamespace = "http://sendEmail.fpt/")
        String to,
        @WebParam(name = "cc", targetNamespace = "http://sendEmail.fpt/")
        String cc,
        @WebParam(name = "bcc", targetNamespace = "http://sendEmail.fpt/")
        String bcc,
        @WebParam(name = "email_id", targetNamespace = "http://sendEmail.fpt/")
        String emailId,
        @WebParam(name = "subject", targetNamespace = "http://sendEmail.fpt/")
        String subject,
        @WebParam(name = "content", targetNamespace = "http://sendEmail.fpt/")
        String content,
        @WebParam(name = "orderid", targetNamespace = "http://sendEmail.fpt/")
        String orderid,
        @WebParam(name = "teamplate", targetNamespace = "http://sendEmail.fpt/")
        String teamplate,
        @WebParam(name = "urlpush", targetNamespace = "http://sendEmail.fpt/")
        String urlpush,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param to
     * @param subject
     * @param bcc
     * @param from
     * @param passWord
     * @param content
     * @param urlpush
     * @param emailId
     * @param attach
     * @param userName
     * @param teamplate
     * @param orderid
     * @param cc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmailAttach", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.SendEmailAttach")
    @ResponseWrapper(localName = "sendEmailAttachResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.SendEmailAttachResponse")
    public String sendEmailAttach(
        @WebParam(name = "from", targetNamespace = "http://sendEmail.fpt/")
        String from,
        @WebParam(name = "to", targetNamespace = "http://sendEmail.fpt/")
        String to,
        @WebParam(name = "cc", targetNamespace = "http://sendEmail.fpt/")
        String cc,
        @WebParam(name = "bcc", targetNamespace = "http://sendEmail.fpt/")
        String bcc,
        @WebParam(name = "email_id", targetNamespace = "http://sendEmail.fpt/")
        String emailId,
        @WebParam(name = "subject", targetNamespace = "http://sendEmail.fpt/")
        String subject,
        @WebParam(name = "content", targetNamespace = "http://sendEmail.fpt/")
        String content,
        @WebParam(name = "attach", targetNamespace = "http://sendEmail.fpt/")
        List<Fileupload> attach,
        @WebParam(name = "orderid", targetNamespace = "http://sendEmail.fpt/")
        String orderid,
        @WebParam(name = "teamplate", targetNamespace = "http://sendEmail.fpt/")
        String teamplate,
        @WebParam(name = "urlpush", targetNamespace = "http://sendEmail.fpt/")
        String urlpush,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param billingPhoneNumber
     * @param loaiSP
     * @param email
     * @param orderNumber
     * @param dateBilling
     * @param nganhHang
     * @param customerFullName
     * @param userName
     * @param sku
     * @param passWord
     * @param productName
     * @param totalPrice
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "order", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.Order")
    @ResponseWrapper(localName = "orderResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.OrderResponse")
    public int order(
        @WebParam(name = "orderNumber", targetNamespace = "http://sendEmail.fpt/")
        String orderNumber,
        @WebParam(name = "sku", targetNamespace = "http://sendEmail.fpt/")
        String sku,
        @WebParam(name = "productName", targetNamespace = "http://sendEmail.fpt/")
        String productName,
        @WebParam(name = "customerFullName", targetNamespace = "http://sendEmail.fpt/")
        String customerFullName,
        @WebParam(name = "billingPhoneNumber", targetNamespace = "http://sendEmail.fpt/")
        String billingPhoneNumber,
        @WebParam(name = "email", targetNamespace = "http://sendEmail.fpt/")
        String email,
        @WebParam(name = "nganhHang", targetNamespace = "http://sendEmail.fpt/")
        String nganhHang,
        @WebParam(name = "loaiSP", targetNamespace = "http://sendEmail.fpt/")
        String loaiSP,
        @WebParam(name = "totalPrice", targetNamespace = "http://sendEmail.fpt/")
        Long totalPrice,
        @WebParam(name = "dateBilling", targetNamespace = "http://sendEmail.fpt/")
        String dateBilling,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param requestId
     * @param userName
     * @param passWord
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkStatus", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.CheckStatus")
    @ResponseWrapper(localName = "checkStatusResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.CheckStatusResponse")
    public String checkStatus(
        @WebParam(name = "request_id", targetNamespace = "http://sendEmail.fpt/")
        String requestId,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param subject
     * @param giaDen
     * @param tgMuaDen
     * @param passWord
     * @param mobileoperator
     * @param content
     * @param nameCamp
     * @param tgMuaTu
     * @param tgGui
     * @param loaiSP
     * @param giaTu
     * @param nganhHang
     * @param userName
     * @param teamplate
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "campaign", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.Campaign")
    @ResponseWrapper(localName = "campaignResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.CampaignResponse")
    public String campaign(
        @WebParam(name = "nameCamp", targetNamespace = "http://sendEmail.fpt/")
        String nameCamp,
        @WebParam(name = "nganhHang", targetNamespace = "http://sendEmail.fpt/")
        String nganhHang,
        @WebParam(name = "loaiSP", targetNamespace = "http://sendEmail.fpt/")
        String loaiSP,
        @WebParam(name = "giaTu", targetNamespace = "http://sendEmail.fpt/")
        Long giaTu,
        @WebParam(name = "giaDen", targetNamespace = "http://sendEmail.fpt/")
        Long giaDen,
        @WebParam(name = "tgMuaTu", targetNamespace = "http://sendEmail.fpt/")
        String tgMuaTu,
        @WebParam(name = "tgMuaDen", targetNamespace = "http://sendEmail.fpt/")
        String tgMuaDen,
        @WebParam(name = "tgGui", targetNamespace = "http://sendEmail.fpt/")
        String tgGui,
        @WebParam(name = "teamplate", targetNamespace = "http://sendEmail.fpt/")
        String teamplate,
        @WebParam(name = "subject", targetNamespace = "http://sendEmail.fpt/")
        String subject,
        @WebParam(name = "content", targetNamespace = "http://sendEmail.fpt/")
        String content,
        @WebParam(name = "mobileoperator", targetNamespace = "http://sendEmail.fpt/")
        String mobileoperator,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param to
     * @param subject
     * @param bcc
     * @param from
     * @param passWord
     * @param content
     * @param urlpush
     * @param campId
     * @param emailId
     * @param userName
     * @param teamplate
     * @param orderid
     * @param cc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmailFull", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.SendEmailFull")
    @ResponseWrapper(localName = "sendEmailFullResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.SendEmailFullResponse")
    public String sendEmailFull(
        @WebParam(name = "from", targetNamespace = "http://sendEmail.fpt/")
        String from,
        @WebParam(name = "to", targetNamespace = "http://sendEmail.fpt/")
        String to,
        @WebParam(name = "cc", targetNamespace = "http://sendEmail.fpt/")
        String cc,
        @WebParam(name = "bcc", targetNamespace = "http://sendEmail.fpt/")
        String bcc,
        @WebParam(name = "email_id", targetNamespace = "http://sendEmail.fpt/")
        String emailId,
        @WebParam(name = "subject", targetNamespace = "http://sendEmail.fpt/")
        String subject,
        @WebParam(name = "content", targetNamespace = "http://sendEmail.fpt/")
        String content,
        @WebParam(name = "orderid", targetNamespace = "http://sendEmail.fpt/")
        String orderid,
        @WebParam(name = "teamplate", targetNamespace = "http://sendEmail.fpt/")
        String teamplate,
        @WebParam(name = "urlpush", targetNamespace = "http://sendEmail.fpt/")
        String urlpush,
        @WebParam(name = "camp_id", targetNamespace = "http://sendEmail.fpt/")
        String campId,
        @WebParam(name = "userName", targetNamespace = "http://sendEmail.fpt/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://sendEmail.fpt/")
        String passWord);

    /**
     * 
     * @param typeTemp
     * @param dateSend
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListReportAuto", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.GetListReportAuto")
    @ResponseWrapper(localName = "getListReportAutoResponse", targetNamespace = "http://sendEmail.fpt/", className = "fpt.sendemail.GetListReportAutoResponse")
    public List<Object> getListReportAuto(
        @WebParam(name = "typeTemp", targetNamespace = "http://sendEmail.fpt/")
        int typeTemp,
        @WebParam(name = "dateSend", targetNamespace = "http://sendEmail.fpt/")
        String dateSend);

}
